# Generated by Django 5.1.6 on 2025-02-26 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_create_question',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 14, 1, 17, 90690)),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 14, 1, 17, 91433)),
        ),
        migrations.AddField(
            model_name='test',
            name='time_create_test',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 14, 1, 17, 90906)),
        ),
    ]
