# Generated by Django 5.1.6 on 2025-02-26 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_question_klass_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='klass_destination',
            field=models.CharField(choices=[('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 50, 0, 411488)),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 50, 0, 412258)),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 50, 0, 411714)),
        ),
    ]
