# Generated by Django 5.1.6 on 2025-02-26 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_test_klass_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 53, 52, 687314)),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 53, 52, 688171)),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 53, 52, 687584)),
        ),
    ]
