# Generated by Django 5.1.6 on 2025-02-27 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_alter_question_time_create_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='repeated_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 43, 50, 111914)),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 43, 50, 113324)),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 43, 50, 112337)),
        ),
    ]
