# Generated by Django 5.1.6 on 2025-02-27 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_test_repeated_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.CharField(choices=[('Txt', 'Кодирование текстов'), ('Value', 'Информационный объём данных'), ('File', 'Файловая система'), ('Net', 'Компьютерные сети'), ('Speed', 'Скорость передачи данных'), ('Graphic', 'Кодирование изображений и звука'), ('IT', 'Редактирование текста'), ('Alg', 'Алгоритмы')], default='Txt', max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 58, 5, 589016)),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 58, 5, 591667)),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 58, 5, 589514)),
        ),
    ]
