# Generated by Django 5.1.6 on 2025-02-27 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_question_topics_alter_question_time_create_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='theme',
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 58, 59, 28352)),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 58, 59, 29850)),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 58, 59, 28847)),
        ),
    ]
