# Generated by Django 5.1.6 on 2025-02-27 18:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_alter_question_time_create_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Вопрос ', max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=256, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='klass_destination',
            field=models.CharField(choices=[('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], default='7', max_length=2, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'True/False'), ('SA', 'Short Answer')], default='SA', max_length=2, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 21, 31, 29, 640071), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=models.CharField(choices=[('Txt', 'Кодирование текстов'), ('Value', 'Информационный объём данных'), ('File', 'Файловая система'), ('Net', 'Компьютерные сети'), ('Speed', 'Скорость передачи данных'), ('Graphic', 'Кодирование изображений и звука'), ('IT', 'Редактирование текста'), ('Alg', 'Алгоритмы')], default='Txt', max_length=128, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='answers',
            field=models.JSONField(verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='right_answer',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Всего'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учащийся'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 21, 31, 29, 641701), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='test',
            name='klass_destination',
            field=models.CharField(choices=[('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], default='7', max_length=2, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='tests.question', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='repeated_answer',
            field=models.BooleanField(default=True, verbose_name='Повторные ответы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 21, 31, 29, 640616), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
