# Generated by Django 5.1.6 on 2025-02-28 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_question_title_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.URLField(default='', verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 8, 40, 43, 143725), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='Вопрос 1', max_length=128),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 8, 40, 43, 144635), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 8, 40, 43, 144018), verbose_name='Создано'),
        ),
    ]
