# Generated by Django 5.1.6 on 2025-02-28 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_question_file_alter_question_time_create_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 11, 5, 14, 140590), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='right_answer',
            field=models.JSONField(verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 11, 5, 14, 141380), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 11, 5, 14, 140836), verbose_name='Создано'),
        ),
    ]
