# Generated by Django 5.1.6 on 2025-02-28 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_alter_question_time_create_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.URLField(blank=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 14, 50, 10, 697675), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Набрано'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 14, 50, 10, 698664), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 14, 50, 10, 697992), verbose_name='Создано'),
        ),
    ]
