# Generated by Django 5.1.6 on 2025-03-03 07:44

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_alter_question_time_create_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 10, 44, 7, 926922), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 10, 44, 7, 927737), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 10, 44, 7, 927196), verbose_name='Создано'),
        ),
    ]
