# Generated by Django 5.1.6 on 2025-03-03 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 35, 504301), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 35, 505038), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 5, 35, 504563), verbose_name='Создано'),
        ),
    ]
