# Generated by Django 5.1.6 on 2025-03-03 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_alter_question_time_create_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 13, 8, 20, 451164), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 13, 8, 20, 452127), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 3, 13, 8, 20, 451604), verbose_name='Создано'),
        ),
        migrations.DeleteModel(
            name='ReportsTests',
        ),
    ]
