# Generated by Django 5.1.6 on 2025-03-06 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_alter_question_time_create_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tmp',
            field=models.BooleanField(default=False, verbose_name='Без заданий (временный тест)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 21, 25, 46, 203251), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 21, 25, 46, 205464), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 21, 25, 46, 204092), verbose_name='Создано'),
        ),
    ]
