# Generated by Django 5.1.6 on 2025-03-12 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_alter_question_time_create_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_create_question',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 10, 11, 6, 586579), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 10, 11, 6, 587324), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='test',
            name='repeated_answer',
            field=models.BooleanField(default=False, verbose_name='Повторные ответы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_create_test',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 10, 11, 6, 586833), verbose_name='Создано'),
        ),
    ]
